name: clustergram
channels:
  - conda-forge
dependencies:
  - scikit-learn
  - scipy
  - seaborn
  - matplotlib
  - bokeh
  - pandas
  - pytest
  - pytest-cov
  - ruff
  - sphinx-book-theme
  - myst-nb
  - numpydoc
  - sphinx
  - sphinx-copybutton
  - pip
  - pip:
      - urbangrammar-graphics
