[build-system]
requires = ["setuptools>=61.0", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[project]
name = "clustergram"
dynamic = ["version"]
authors = [
    { name = "Martin Fleischmann", email = "martin@martinfleischmann.net" },
]
maintainers = [{ name = "Martin Fleischmann" }]
license = "MIT"
description = "Clustergram - visualization and diagnostics for cluster analysis"
readme = "README.md"
classifiers = [
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
requires-python = ">=3.10"
dependencies = ["pandas", "numpy", "matplotlib"]

[project.optional-dependencies]
all = ["bokeh", "scikit-learn", "scipy"]
test = ["bokeh", "pytest", "scikit-learn", "scipy"]

[project.urls]
Home = "https://clustergram.readthedocs.io"
Repository = "https://github.com/martinfleis/clustergram"

[tool.setuptools.packages.find]
include = ["clustergram", "clustergram.*"]

[tool.coverage.run]
omit = ["clustergram/test_clustergram.py"]
source = ['clustergram']

[tool.coverage.report]
exclude_lines = ["except ImportError"]
ignore_errors = true
omit = ["clustergram/test_clustergram.py"]

[tool.ruff]
line-length = 88
exclude = ["doc"]

[tool.ruff.lint]
select = ["E", "F", "W", "I", "UP", "N", "B", "A", "C4", "SIM", "ARG"]
ignore = ["B006"]
