name: clustergram_docs
channels:
  - conda-forge
dependencies:
  - pandas
  - matplotlib
  - bokeh
  - scikit-learn
  - scipy
  - seaborn
  - pydata-sphinx-theme
  - myst-nb
  - numpydoc
  - sphinx
  - pip
  - pip:
    - urbangrammar-graphics